language: cpp
compiler:
- gcc
install:
- wget -O arduino-1.5.8-linux64.tgz http://arduino.cc/download.php?f=/arduino-1.5.8-linux64.tgz
- tar -xvf arduino-1.5.8-linux64.tgz
- sudo mv arduino-1.5.8/ /usr/local/share/arduino
- sudo apt-get update && sudo apt-get install -y ia32-libs
- git clone -b ide1.5x https://github.com/justonia/ino.git
- cd ino && sudo make install && cd ../
- sudo pip install jinja2
- sudo pip install pyserial
